### ISSUE TITLE
401 or 403 should return header "X-Shopify-API-Request-Failure-Reauthorize-Url"

### ISSUE THREAD

**Issue by Waynenabors** [hez/elixir-shopify-admin-proxy#11]
Shopify App Bridge authenticated fetch supports auto redirecting to an install/reauth url when a token expires or is missing scopes by setting the response header string to something like `X-Shopify-API-Request-Failure-Reauthorize-Url`.

The documentation is hard to find but here is the spec:

```
export interface AuthenticatedFetchOptions {
    /**
     * The fetch function to perform the network call.
     */
    fetchOperation?: FetchOperation;
    /**
     * The URL to redirect to when the session token is invalid.
     * If not provided, `requestFailureReauthorizeUrlHeader` will be used.
     */
    reauthorizeUrl?: string;
    /**
     * The Header parameter.
     */
    requestFailureReauthorizeUrlHeader: string;
}
```

We could add `|> put_resp_header("X-Shopify-API-Request-Failure-Reauthorize-Url", install_url)` to https://github.com/hez/elixir-shopify-admin-proxy/blob/3f4b6349f22993dd6b3b4611009f84226982447f/lib/shopify_admin_proxy.ex#L66 or even specify the difference between unauthorized and forbidden.

**Comment by hez** [comment]
This is handled by https://github.com/orbit-apps/elixir-shopifyapi/blob/main/lib/shopify_api/plugs/auth_shop_session_token.ex

Going to close this.
